# https://taskfile.dev

version: '3'

vars:
  FX_NAME: stutter
  FX_SLOT: 0
  MIDI_SLOT_IN: 1
  MIDI_SLOT_OUT: 1
tasks:
  show:
    cmds:
    - ../../../tools/logue-cli/logue-cli-linux64-0.07-2b/logue-cli probe -m modfx -i {{.MIDI_SLOT_IN}} -o {{.MIDI_SLOT_OUT}}
  probe:
    cmds:
    - ../../../tools/logue-cli/logue-cli-linux64-0.07-2b/logue-cli probe -l
  clear:
    cmds:
    - ../../../tools/logue-cli/logue-cli-linux64-0.07-2b/logue-cli clear -m modfx -s {{.FX_SLOT}} -i {{.MIDI_SLOT_IN}} -o {{.MIDI_SLOT_OUT}}
  load:
    cmds:
     - ../../../tools/logue-cli/logue-cli-linux64-0.07-2b/logue-cli load -i {{.MIDI_SLOT_IN}} -o {{.MIDI_SLOT_OUT}} -u {{.FX_NAME}}.ntkdigunit -s {{.FX_SLOT}}
  make:
    cmds:
    - make
    - ../../../tools/logue-cli/logue-cli-linux64-0.07-2b/logue-cli clear -m modfx -s {{.FX_SLOT}} -i {{.MIDI_SLOT_IN}} -o {{.MIDI_SLOT_OUT}}
    - ../../../tools/logue-cli/logue-cli-linux64-0.07-2b/logue-cli load -i {{.MIDI_SLOT_IN}} -o {{.MIDI_SLOT_OUT}} -u {{.FX_NAME}}.ntkdigunit -s {{.FX_SLOT}}


  default:
    cmds:
      - echo "Commands - show | probe | load | make"
    silent: true
